name: testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test
        run: |
          touch foo.md
          git config --global user.name "bot"
          git config --global user.email "foo@example.com"
          git switch -c foobar
          git add -N .
          git add -A
          git commit -m "add foo.md"
          body="generated\ntrigger commit: ${{ env.GITHUB_SHA }}"
          gh pr create --title "add foo.md" --body="${body}"
